---

- name: Create a health check for route53 for the first region
  route53_health_check:
    state: present
    fqdn: "{{ hostvars[(groups[aws_profile] | last )].springappelb_name }}"
    type: HTTP_STR_MATCH
    resource_path: /hello
    string_match: "hello"
    request_interval: 10
    failure_threshold: 2
  register: my_health_check

- name: Add our dns record to route53 for the first region
  route53:
    state: present
    zone: "{{ route53_zone }}"
    type: A
    record: "{{ hello_dns }}"
    value: "{{ hostvars[(groups[aws_profile] | last )].springappelb_name }}"
    ttl: 30
    identifier: "{{ aws_profile }}@www"
    weight: 100
    health_check: "{{ my_health_check.health_check.id }}"
    alias: True
    alias_hosted_zone_id: "{{ hostvars[(groups[aws_profile] | last )].springappelb_zone }}"
    alias_evaluate_target_health: True
  register: route_53_debug

- debug: var=route_53_debug

- name: Create a health check for route53 for the second region
  route53_health_check:
    state: present
    fqdn: "{{ hostvars[(groups[aws_profile_2] | last )].springappelb_name }}"
    type: HTTP_STR_MATCH
    resource_path: /hello
    string_match: "hello"
    request_interval: 10
    failure_threshold: 2
  register: my_health_check_2
  when: aws_profile_2 is defined

- name: Add our dns record to route53 for the second region
  route53:
    state: present
    zone: "{{ route53_zone }}"
    type: A
    record: "{{ hello_dns }}"
    value: "{{ hostvars[(groups[aws_profile_2] | last )].springappelb_name }}"
    ttl: 20
    identifier: "{{ aws_profile_2 }}@www"
    weight: 200
    health_check: "{{ my_health_check_2.health_check.id }}"
    alias: True
    alias_hosted_zone_id: "{{ hostvars[(groups[aws_profile_2] | last )].springappelb_zone }}"
    alias_evaluate_target_health: True
  when: aws_profile_2 is defined  



