---

- local_action: stat path=~/.ssh/{{ aws_key_name }}.pub
  register: pubkey_file
  become: no
  changed_when: False
  tags:
    - ec2_key 

- name: Create SSH key pair
  shell: >
    ssh-keygen -q -t rsa -b 4096 -N '' -C "" -f ~/.ssh/{{ aws_key_name }}
  when: pubkey_file.stat.exists == false
  tags:
    - ec2_key 

- name: Assign EC2 Key
  ec2_key:
    name:             "{{ aws_key_name }}"
    profile:          "{{ aws_profile }}"
    key_material:     "{{ item }}"
    state:            present
  with_file: "~/.ssh/{{ aws_key_name }}.pub"
  tags:
    - ec2_key 